server:
  port: 8010
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DreamCloudz/cloud-config/  #设置github上配置文件路径
          search-paths: conf
          username:
          password:
      label: master
      fail-fast: true

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8001/eureka/
