server:
  port: 8010
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/conf
  profiles:
    active: native  # 设置本地存储配置 spring.profiles.active=native

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8001/eureka/
