server:
  port: 8005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
# \u6DFB\u52A0\u7194\u65AD\u5668
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: cloud-service-feign

